### ISSUE TITLE
User can save favorite movies

### ISSUE THREAD

**Issue by stevebrownlee** [nss-malicious-mongongos/nutshell#2]
# Story

As a user, I should be able to create a list of my favorite movies. I should be able to track the movie title, the lead actor, and the year it was released. I should also be able to edit individual items.

# Acceptance Criteria

**Given** a user wants to show a favorite movie on their dashboard
**When** the user performs a gesture on a `New Movie` affordance
**Then** a form should be presented to the user in which the following information can be entered

1. Movie title
1. Lead actor
1. Year released

**Given** a user has entered in all field values for storing a new movie
**When** the user performs a gesture on the `Save Movie` affordance
**Then** the movie should be saved in the database, and assigned to the user
**And** should have a property of the current timestamp

**Given** a user has saved some movies
**When** the user visits their dashboard
**Then** the movies should be presented in the `Favorite Movies` components, sorted by date in descending order
**And** each movie should have an affordance to delete the movie

**Given** a user wants to remove a previously stored movie
**When** the user performs a gesture on the delete affordance
**Then** the movie should be deleted

**Given** a user wants to change the details of a movie
**When** the user performs a gesture to edit the movie
**Then** the user should be presented with a form that has the movie details pre-filled into the fields
**And** there should be an affordance to save the new details

**Comment by RDilly** [comment]
**_FINISSSHHHEEEDDDDDD_**

Did not think i was going to accomplish that in under 48hrs.
I'm very happy with the work.
